### ISSUE TITLE
Add get-auth URL as a separate item in the nav

### ISSUE THREAD

**Issue by eknee** [davidbenge/depdevkit#4]
Expose the get-auth URL in the left nav for users to be able to see where they can go to get authentication.  The page should contain the following:

- URL endpoint to use in postman
- Example call/response
- response definition

**Comment by davidbenge** [comment]
So did you want like a page dedicated to Auth?  and on that page is the url and the how to cut and paste for POSTMAN

**Comment by davidbenge** [comment]
here is a rough draft 
https://experience.adobe.com/?devMode=true#/custom-apps/?localDevUrl=https://27200-depdevkit-stage.adobeio-static.net/index.html

I really need some style on the code and json.  I will clean up the style. 
Give me your feedback.  Is this what your thinking or do you want a form too?

**Comment by davidbenge** [comment]
put in a better look and new edit component 

https://experience.adobe.com/?devMode=true#/custom-apps/?localDevUrl=https://27200-depdevkit-stage.adobeio-static.net/index.html

check it out
@eknee

**Comment by eknee** [comment]
![image](https://user-images.githubusercontent.com/6667779/162265574-55e2fbec-c0ec-4d00-a18c-6b841572abea.png)

- Make the formatting updates for the auth url
- remove the page header completely

**Comment by davidbenge** [comment]
Done and in production
